[package]
name = "string_chunker_helper"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "string_chunker_helper"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.26.0"
bstr = "1"
